version: '3.3'

networks:

  app-tier:
    driver: bridge

services:

  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:80"
    volumes:
      - api-sync:/var/www:rw
    networks:
      - app-tier

  mysql:
    image: mysql:5.7
    environment:
      - MYSQL_ROOT_PASSWORD=123
      - MYSQL_DATABASE=api
      - MYSQL_USER=api
      - MYSQL_PASSWORD=123
    volumes:
      - ./../.mysql:/var/lib/mysql
      - ./.docker/custom.cnf:/etc/mysql/conf.d/custom.cnf
    networks:
      - app-tier

  redis:
    image: redis:latest
    networks:
      - app-tier

volumes:
  api-sync:
    external: true
