<?php
/**
 * Based on
 *   https://codepen.io/colorlib/pen/rxddKy
 */

    use Laminas\Authentication\Result as AuthenticationResult;

    $this->layout()->setTemplate('layout/login');
?>

<div class="container" style="margin-top: 10px;">
  <div class="row">
    <div class="col-md-4 offset-md-4 bg-info rounded">
      <h3 class="text-center" style="padding-top: 10px;">API</h3>
      <?php
        if ($this->result) {
            switch ($this->result) {
                case AuthenticationResult::FAILURE_IDENTITY_NOT_FOUND:
                    echo '<div class="alert alert-danger">Invalid email</div>';
                    break;
                case AuthenticationResult::FAILURE_CREDENTIAL_INVALID:
                    echo '<div class="alert alert-danger">Invalid password</div>';
                    break;
                case AuthenticationResult::FAILURE_UNCATEGORIZED:
                    echo '<div class="alert alert-danger">Authentication Failed</div>';
                    break;
            }
        }
      ?>

      <form method="POST">
        <div class="text-left" style="margin-top: 1em;">
          <label for="email" class="badge badge-secondary">Email</label>
          <div class="input-group">
            <input class="form-control" type="text" name="email" value="<?= $this->escapeHtml($this->email); ?>">
          </div>

          <label for="password" class="badge badge-secondary" style="margin-top: 2em;">Password</label>
          <div class="input-group">
            <input class="form-control" type="password" name="password"/>
          </div>
        </div>
        <div class="text-right">
          <button style="margin: 1em;" class="btn btn-secondary"><i class="fas fa-user-lock"></i> Login</button>
        </div>
      </form>
    </div>
  </div>
</div>


<script>
$('email').focus();
</script>
