<!DOCTYPE html>
  <html lang="en">
  <head>
    <meta charset="utf-8">
    <title>Laminas API Tools Doctrine Skeleton</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">

    <link href="/css/bootstrap.min.css" media="screen" rel="stylesheet" type="text/css">
    <link href="/css/style.css" media="screen" rel="stylesheet" type="text/css">
    <link href="/img/favicon.ico" rel="shortcut icon" type="image/vnd.microsoft.icon">

    <script type="text/javascript" src="/js/jquery-3.5.1.min.js"></script>
    <script type="text/javascript" src="/js/bootstrap.min.js"></script>
  </head>
  <body>
    <div class="container">
      <?= $this->content ?>
    </div>
  </body>
</html>
