<?php
/**
 * This file was autogenerated by zfcampus/zf-mvc-auth (bin/zf-mvc-auth-oauth2-override.php),
 * and overrides the ZF\OAuth2\Service\OAuth2Server to provide the ability to create named
 * OAuth2\Server instances.
 */
return [
    'service_manager' => [
        'factories' => [
            'Laminas\ApiTools\OAuth2\Service\OAuth2Server' => 'Laminas\ApiTools\MvcAuth\Factory\NamedOAuth2ServerFactory',
        ],
    ],
    'api-tools-mvc-auth' => [
        'authentication' => [
            'adapters' => [

                // OAuth2 adapter, using a named "storage" service
                'oauth_doctrine' => [
                    'adapter' => 'Laminas\ApiTools\MvcAuth\Authentication\OAuth2Adapter',
                    'storage' => [
                        'storage' => 'oauth2.doctrineadapter.default',
                        'route' => '/oauth',
                    ],
                ],

                'user' => [
                    'adapter' => 'User\Authentication\Adapter\DoctrineAdapter',
                    'storage' => [
                        'Zend\Authentication\Storage\Session',
                    ],
                ],
            ],
        ],
    ],
];
